import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navigation from '../components/navigation/navigation'
import { Navbar } from 'react-bootstrap'
import logo from "../../public/logo.png"
import Link from 'next/link'
import ImageGallery from 'react-image-gallery';

import { BrandFacebook, BrandYoutube, BrandInstagram, BrandLinkedin } from 'tabler-icons-react';


const inter = Inter({ subsets: ['latin'] })


const images = [
  {
    original: 'https://picsum.photos/id/1018/1000/600/',
    thumbnail: 'https://picsum.photos/id/1018/250/150/',
  },
  {
    original: 'https://picsum.photos/id/1015/1000/600/',
    thumbnail: 'https://picsum.photos/id/1015/250/150/',
  },
  {
    original: 'https://picsum.photos/id/1019/1000/600/',
    thumbnail: 'https://picsum.photos/id/1019/250/150/',
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Kizuna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <navbar className={styles.nav}>
          <Image src={logo} className={styles.logo} />

          <ul>
            <li><Link href={"#"}>Games</Link></li>
            <li><Link href={"#"}>Our Story</Link></li>
            <li><Link href={"#"}>Support</Link></li>
            <li><Link href={"#"}>Contact</Link></li>
            <li><Link href={"#"}><BrandFacebook size={24} color={"black"} /></Link></li>
            <li><Link href={"#"}><BrandYoutube size={24} color={"black"} /></Link></li>
            <li><Link href={"#"}><BrandInstagram size={24} color={"black"} /></Link></li>
            <li><Link href={"#"}><BrandLinkedin size={24} color={"black"} /></Link></li>
            {/* <li><Link href={"#"}>Games</Link></li> */}
          </ul>
        </navbar>

        <section className={styles.hero}>
          <div className={styles.title}>
            <h1>Kizuna</h1>
            <h1>Labs</h1>
            <p>Makers of your favorite games like:
              Slice It All, Pancake Art, Volleybeans and Farm It.
            </p>
            <a className={styles.btn}>
              DISCOVER OUR GAMES
            </a>
          </div>

        </section>

        <section className={styles.game}>
          <ImageGallery items={images} showNav={false} showPlayButton={false} />;

          <div className={styles.game_section}>
            <h2>Space Hopper</h2>
            <p>Space Hopper is a thrilling hyper casual game set in a post-apocalyptic sci-fi universe. Players take on the role of a brave astronaut who must hop from one damaged spaceship to another in order to survive. With each successful hop, players must navigate through a variety of obstacles, such as broken machinery and dangerous space debris. As they progress, players collect valuable resources and power-ups to help them on their journey. With its intuitive controls and addictive gameplay, Space Hopper is the ultimate test of skill and agility in a universe where danger lurks around every corner.</p>
          </div>

        </section>
      </main>
    </>
  )
}
